version: '3'
services:
  redis:
    container_name: redis_service
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
  postgresql:
    container_name: postgres_service
    depends_on:
      - redis
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped
  commandergql:
    container_name: commandergql_service
    depends_on:
      - redis
      - postgresql
    build: CommanderGQL/
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_URLS=http://+
      - ASPNETCORE_ENVIRONMENT=Development
